In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Data.csv')

In [3]:
data

Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0       Yes
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0        No
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       Yes
14  Sri lanka  33.0  22000.0        No

In [4]:
X = data.iloc[:,:-1]
X

Country   Age   Salary
0       India  34.0  92000.0
1   Sri lanka  22.0  25000.0
2       China  31.0  74000.0
3   Sri lanka  29.0      NaN
4       China  55.0  98000.0
5       India  24.0  30000.0
6   Sri lanka  28.0  40000.0
7       India   NaN  60000.0
8       China  51.0  89000.0
9       India  44.0  78000.0
10  Sri lanka  21.0  20000.0
11      China  25.0  30000.0
12      India  33.0  45000.0
13      India  42.0  65000.0
14  Sri lanka  33.0  22000.0

In [5]:
Y = data.iloc[:,-1]  #target class

In [6]:
Y

0     Yes
1     Yes
2     Yes
3      No
4     Yes
5      No
6      No
7      No
8     Yes
9     Yes
10     No
11    Yes
12    Yes
13    Yes
14     No
Name: Purchased, dtype: object

# Handling Missing Data

In [7]:
import numpy as np
from sklearn.impute import SimpleImputer
# from sklearn.preprocessing import Imputer

In [8]:
imputer = SimpleImputer(missing_values = np.nan,strategy ='mean')

In [9]:
X

Country   Age   Salary
0       India  34.0  92000.0
1   Sri lanka  22.0  25000.0
2       China  31.0  74000.0
3   Sri lanka  29.0      NaN
4       China  55.0  98000.0
5       India  24.0  30000.0
6   Sri lanka  28.0  40000.0
7       India   NaN  60000.0
8       China  51.0  89000.0
9       India  44.0  78000.0
10  Sri lanka  21.0  20000.0
11      China  25.0  30000.0
12      India  33.0  45000.0
13      India  42.0  65000.0
14  Sri lanka  33.0  22000.0

In [10]:
imputer.fit(X.iloc[:,1:3])

SimpleImputer()

In [11]:
X.iloc[:,1:3] = imputer.transform(X.iloc[:,1:3])

In [12]:
print(X)

      Country        Age        Salary
0       India  34.000000  92000.000000
1   Sri lanka  22.000000  25000.000000
2       China  31.000000  74000.000000
3   Sri lanka  29.000000  54857.142857
4       China  55.000000  98000.000000
5       India  24.000000  30000.000000
6   Sri lanka  28.000000  40000.000000
7       India  33.714286  60000.000000
8       China  51.000000  89000.000000
9       India  44.000000  78000.000000
10  Sri lanka  21.000000  20000.000000
11      China  25.000000  30000.000000
12      India  33.000000  45000.000000
13      India  42.000000  65000.000000
14  Sri lanka  33.000000  22000.000000


# Feature Selection

In [13]:
print(X)

      Country        Age        Salary
0       India  34.000000  92000.000000
1   Sri lanka  22.000000  25000.000000
2       China  31.000000  74000.000000
3   Sri lanka  29.000000  54857.142857
4       China  55.000000  98000.000000
5       India  24.000000  30000.000000
6   Sri lanka  28.000000  40000.000000
7       India  33.714286  60000.000000
8       China  51.000000  89000.000000
9       India  44.000000  78000.000000
10  Sri lanka  21.000000  20000.000000
11      China  25.000000  30000.000000
12      India  33.000000  45000.000000
13      India  42.000000  65000.000000
14  Sri lanka  33.000000  22000.000000


In [14]:
X = X.iloc[:,1:] # getting out Country column
print(X)

          Age        Salary
0   34.000000  92000.000000
1   22.000000  25000.000000
2   31.000000  74000.000000
3   29.000000  54857.142857
4   55.000000  98000.000000
5   24.000000  30000.000000
6   28.000000  40000.000000
7   33.714286  60000.000000
8   51.000000  89000.000000
9   44.000000  78000.000000
10  21.000000  20000.000000
11  25.000000  30000.000000
12  33.000000  45000.000000
13  42.000000  65000.000000
14  33.000000  22000.000000


In [15]:
# feature encoding for Purchased column
print(Y)

0     Yes
1     Yes
2     Yes
3      No
4     Yes
5      No
6      No
7      No
8     Yes
9     Yes
10     No
11    Yes
12    Yes
13    Yes
14     No
Name: Purchased, dtype: object


In [16]:
from sklearn import preprocessing

In [17]:
le = preprocessing.LabelEncoder()

In [18]:
le.fit(Y)

LabelEncoder()

In [19]:
Y =le.transform(Y)

In [20]:
print(Y)

[1 1 1 0 1 0 0 0 1 1 0 1 1 1 0]


# Handling Imbalanced Data

In [21]:
# pip install imblearn

# UnderSampling

In [22]:
from imblearn.under_sampling import RandomUnderSampler

In [23]:
rus = RandomUnderSampler(random_state = 42)

In [24]:
X,Y = rus.fit_resample(X, Y)

In [25]:
# print(X)
print(Y)

[0 0 0 0 0 0 1 1 1 1 1 1]


# Over Sampling

In [26]:
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler 

In [27]:
rus = RandomOverSampler(random_state = 42)
X,Y = rus.fit_resample(X, Y)

In [28]:
# print(X)
print(Y)

[0 0 0 0 0 0 1 1 1 1 1 1]


# Train-Test Split

In [29]:
import numpy as np
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size =0.2, random_state =42)

In [31]:
X_train,X_test

(          Age   Salary
 8   44.000000  78000.0
 5   33.000000  22000.0
 2   28.000000  40000.0
 1   24.000000  30000.0
 11  31.000000  74000.0
 4   21.000000  20000.0
 7   22.000000  25000.0
 3   33.714286  60000.0
 6   33.000000  45000.0,
      Age        Salary
 10  42.0  65000.000000
 9   34.0  92000.000000
 0   29.0  54857.142857)

# Feature Scaling

Standardization : (x - mean(X)) / std(X)   >>> Ranges between -4 to 4

Normalization : (x - min(x)) / (max(x)-min(x))  >>>>>> Ranges between -1 to 1

In [32]:
from sklearn import preprocessing

In [33]:
sc = preprocessing.StandardScaler()

In [34]:
sc.fit(X_train)

StandardScaler()

In [35]:
X_train = sc.transform(X_train)

In [36]:
X_train

array([[ 2.06940088,  1.63446408],
       [ 0.44712168, -1.0401135 ],
       [-0.29027795, -0.18042785],
       [-0.88019766, -0.65803099],
       [ 0.15216183,  1.44342282],
       [-1.32263744, -1.13563413],
       [-1.17515751, -0.89683256],
       [ 0.55246449,  0.77477843],
       [ 0.44712168,  0.05837372]])

In [37]:
X_test = sc.transform(X_test)
# X_test